name: foresight
description: Graduation porject clone from Web to Flutter.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <3.1.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  lottie: ^2.3.2
  flutter_screenutil: ^5.8.1
  http: ^0.13.6
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  flutter_image_slideshow: ^0.1.5
  flutter_custom_clippers: ^2.1.0
  retry: ^3.1.2
  awesome_snackbar_content: ^0.1.3
  skeletons: ^0.0.3
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

